const z=612,v=792,X=40,u=new TextEncoder,C=(n="")=>String(n??"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^\x20-\x7E]/g," ").replace(/\s+/g," ").trim(),q=(n="")=>C(n).replace(/\\/g,"\\\\").replace(/\(/g,"\\(").replace(/\)/g,"\\)"),h=(n="",o=20)=>{const a=C(n);return a.length>o?`${a.slice(0,o-1)}.`:a},W=(n="")=>{const[,o=""]=n.match(/^data:image\/jpeg;base64,(.+)$/)||[];if(!o)return null;const a=atob(o),c=new Uint8Array(a.length);for(let p=0;p<a.length;p+=1)c[p]=a.charCodeAt(p);return c},T=n=>{const o=n.reduce((p,A)=>p+A.length,0),a=new Uint8Array(o);let c=0;return n.forEach(p=>{a.set(p,c),c+=p.length}),a},r=(n,o,a,c)=>`BT /F1 ${a} Tf ${n} ${o} Td (${q(c)}) Tj ET
`,P=(n,o,a,c)=>`${n} ${o} m ${a} ${c} l S
`,U=(n,o,a,c)=>`${n} ${o} ${a} ${c} re S
`;function K(n=new Date){const o=a=>String(a).padStart(2,"0");return["MAN",n.getFullYear(),o(n.getMonth()+1),o(n.getDate()),o(n.getHours()),o(n.getMinutes()),o(n.getSeconds())].join("-")}function Q({folio:n,paqueteria:o,fecha:a,hora:c,responsableEntrega:p,nombreRecibe:A,pedidos:S=[],firmaDataUrl:_,firmaAncho:j=900,firmaAlto:O=260}){const l=W(_),G=[];let t=null,e=752;const y=()=>{t=[],G.push(t),e=752,t.push(r(40,e,16,"SILOGEC - Manifiesto de entrega a paqueteria")),e-=22,t.push(r(40,e,10,`Folio: ${n}`)),t.push(r(250,e,10,`Fecha: ${a} ${c}`)),e-=16,t.push(r(40,e,10,`Paqueteria recolectora: ${o}`)),t.push(r(250,e,10,`Entrega: ${p||"SILOGEC"}`)),e-=22,t.push(P(40,e,572,e)),e-=18,t.push(r(40,e,9,"#")),t.push(r(62,e,9,"Pedido")),t.push(r(150,e,9,"Guia")),t.push(r(292,e,9,"Paqueteria")),t.push(r(386,e,9,"Estatus")),t.push(r(460,e,9,"Lote")),e-=8,t.push(P(40,e,572,e)),e-=16},b=s=>{e-s<40&&y()};y(),S.forEach((s,i)=>{b(18),t.push(r(40,e,8,String(i+1))),t.push(r(62,e,8,h(s.pedido,17))),t.push(r(150,e,8,h(s.guia,27))),t.push(r(292,e,8,h(s.paqueteria,17))),t.push(r(386,e,8,h(s.estatus,13))),t.push(r(460,e,8,h(s.lote||"SIN LOTE",20))),e-=16}),b(145),e-=8,t.push(P(40,e,572,e)),e-=20,t.push(r(40,e,10,`Total de piezas documentadas: ${S.length}`)),e-=18,t.push(r(40,e,10,`Recibe paqueteria: ${A||"Sin nombre capturado"}`)),e-=18,t.push(r(40,e,10,"Firma de recepcion:")),e-=96,t.push(U(40,e,240,78)),l&&t.push(`q 220 0 0 62 50 ${e+8} cm /Sig Do Q
`),e-=16,t.push(r(40,e,8,"Comprobante temporal generado en SILOGEC."));const f=3;let R=4;const F=l?R++:null,M=G.map(()=>({pageId:R++,contentId:R++})),E=2,H=1,I=[],d=(s,i)=>{I.push({id:s,bytes:typeof i=="string"?u.encode(i):i})};d(H,`<< /Type /Catalog /Pages ${E} 0 R >>`),d(E,`<< /Type /Pages /Kids ${M.map(s=>`${s.pageId} 0 R`).join(" ")} /Count ${M.length} >>`),d(f,"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>"),l&&d(F,T([u.encode(`<< /Type /XObject /Subtype /Image /Width ${j} /Height ${O} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${l.length} >>
stream
`),l,u.encode(`
endstream`)])),G.forEach((s,i)=>{const g=M[i],D=u.encode(s.join("")),w=l?`<< /Font << /F1 ${f} 0 R >> /XObject << /Sig ${F} 0 R >> >>`:`<< /Font << /F1 ${f} 0 R >> >>`;d(g.pageId,`<< /Type /Page /Parent ${E} 0 R /MediaBox [0 0 612 792] /Resources ${w} /Contents ${g.contentId} 0 R >>`),d(g.contentId,T([u.encode(`<< /Length ${D.length} >>
stream
`),D,u.encode("endstream")]))}),I.sort((s,i)=>s.id-i.id);const $=[u.encode(`%PDF-1.4
`)],x=[0];let m=$[0].length;I.forEach(s=>{x[s.id]=m;const i=u.encode(`${s.id} 0 obj
`),g=u.encode(`
endobj
`);$.push(i,s.bytes,g),m+=i.length+s.bytes.length+g.length});const B=m,N=Math.max(...I.map(s=>s.id)),L=["xref",`0 ${N+1}`,"0000000000 65535 f ",...Array.from({length:N},(s,i)=>{const g=x[i+1]||0;return`${String(g).padStart(10,"0")} 00000 n `}),"trailer",`<< /Size ${N+1} /Root ${H} 0 R >>`,"startxref",String(B),"%%EOF"].join(`
`);return $.push(u.encode(L)),new Blob([T($)],{type:"application/pdf"})}const Y=n=>new Promise((o,a)=>{const c=new FileReader;c.onload=()=>o(c.result),c.onerror=a,c.readAsDataURL(n)});export{Y as blobADataUrl,K as crearFolioManifiesto,Q as generarManifiestoPdf};
